env:
    contexts:
        - authentication:
            method: script
            parameters:

                script: "dast-config/testfire_auth.js"
                scriptEngine: "ECMAScript : Graal.js"
                usernameKey: "uid"
                passwordKey: "passw"
                loginURL: http://testfire.net/doLogin

            verification:
                loggedInRegex: Sign off
                loggedOutRegex: Sign In
                method: poll
                pollFrequency: 60
                pollPostData: ""
                pollUnits: requests
                pollUrl: http://testfire.net/bank/transfer.jsp
          excludePaths:
            - http://testfire.net/.*jsp
            - http://testfire.net/.*js
            - http://testfire.net/.*png
            - http://testfire.net/.*jpg
          includePaths:
            - http://testfire.net.*
          name: testfire
          sessionManagement:
            method: cookie
            parameters: {}
          technology:
            exclude: []
          urls:
            - http://testfire.net
          users:
            - credentials:
                password: admin
                username: admin
              name: Admin
    parameters:
        failOnError: true
        failOnWarning: false
        progressToStdout: true
    vars: {}
jobs:
    - parameters:
        action: "add"
        type: "authentication"
        engine: "ECMAScript : Graal.js"
        name: "testfire_auth"

        file: "dast-config/testfire_auth.js"

        target: ""
        inline: ""
      name: "script"
      type: "script"
    - name: passiveScan-config
      parameters:
        enableTags: false
        maxAlertsPerRule: 0
        maxBodySizeInBytesToScan: 0
        scanOnlyInScope: true
      rules: []
      type: passiveScan-config
    - name: spiderAjax
      parameters:
        context: testfire
        maxCrawlDepth: 2
        maxDuration: 60
        numberOfBrowsers: 4
        runOnlyIfModern: false
        user: Admin
      type: spiderAjax
    - name: passiveScan-wait
      parameters: {}
      type: passiveScan-wait
    - name: activeScan
      parameters:
        addQueryParam: false
        context: testfire
        delayInMs: 0
        handleAntiCSRFTokens: false
        injectPluginIdInHeader: false
        maxRuleDurationInMins: 0
        maxScanDurationInMins: 0
        policy: ""
        scanHeadersAllRequests: false
        threadPerHost: 5
        user: Admin
      policyDefinition:
        defaultStrength: medium
        defaultThreshold: medium
        rules: []
      type: activeScan
    - name: report
      parameters:
        reportDir: /home/ubuntu/output/dast-output-1230056092
        reportFile: ZAP-Report
        template: traditional-json-plus
      type: report
